# Generated by Django 6.0.2 on 2026-02-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_land_latitude_land_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='auction_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
