# Generated by Django 6.0.2 on 2026-02-20 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('county', models.CharField(choices=[('nakuru', 'Nakuru'), ('kiambu', 'Kiambu'), ('narok', 'Narok'), ('laikipia', 'Laikipia'), ('uasin-gishu', 'Uasin Gishu'), ('kilifi', 'Kilifi'), ('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('size_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('leased', 'Leased'), ('pending', 'Pending')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('has_water', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_road_access', models.BooleanField(default=False)),
                ('has_fencing', models.BooleanField(default=False)),
                ('has_irrigation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('leading', 'Leading'), ('outbid', 'Outbid'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.land')),
            ],
            options={
                'ordering': ['-amount_kes'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_type', models.CharField(choices=[('lease', 'Lease Payment'), ('investment', 'Investment'), ('refund', 'Refund'), ('bid', 'Bid Deposit')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mpesa_ref', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
